# Configurações do banco de dados PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/ecommerceapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Configurações do Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update